### ISSUE TITLE
Provide a way to mimic AR associations

### ISSUE THREAD

**Issue by inem** [aishek/nihilist#4]
If you have associations in your original model, then in order to make your code work well with Null object you need to fo something like this:

```ruby
class NullCompany
  include Nigilist

  def devices
    Device.none
  end
end
```

I am not sure if it makes sense to add this functionality, but at least it worth mentioning in Readme

**Comment by aishek** [comment]
It will make things more complex: need to provide User model, then guess somehow about association classes, then return none for each association. Maybe it is fine, and almost every project have User model as opposite to Guest model, but still.

So mention in Readme will be enough I think.

**Comment by aishek** [comment]
#5
